const FALLBACK_BTC_TOKEN_ADDRESS =
  "0x04861ba938aed21f2cd7740acd3765ac4d2974783a3218367233de0153490cb6";
const FALLBACK_BTC_TOKEN_SYMBOL = "BTC";
const FALLBACK_BTC_TOKEN_DECIMALS = 8;

export const BTC_TOKEN_ADDRESS =
  process.env.EXPO_PUBLIC_BTC_TOKEN_ADDRESS || FALLBACK_BTC_TOKEN_ADDRESS;
export const BTC_TOKEN_SYMBOL =
  process.env.EXPO_PUBLIC_BTC_TOKEN_SYMBOL || FALLBACK_BTC_TOKEN_SYMBOL;
export const BTC_TOKEN_DECIMALS = Number(
  process.env.EXPO_PUBLIC_BTC_TOKEN_DECIMALS ||
    String(FALLBACK_BTC_TOKEN_DECIMALS),
);

export const ESCROW_CONTRACT_ADDRESS =
  process.env.EXPO_PUBLIC_ESCROW_CONTRACT_ADDRESS || "";
